name: Build and Deploy

on:
    # Runs on pushes targeting the default branch
    push:
        branches: ['master']

    repository_dispatch:

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build-and-deploy:
        name: Build and deploy Gatsby site
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
                  cache: 'npm'

            - name: Install Project Dependencies
              run: npm ci

            - name: Install Gatsby CLI
              run: npm install -g gatsby-cli@2.12.34

            - name: Cleanup
              run: npm run clean

            - name: Build project
              run: npm run build

            - name: Verify build
              run: ls -la public
