name: Build and Deploy

on:
    push:
        branches: ['master']

    repository_dispatch:
        types: [wp_update]

    workflow_dispatch:

jobs:
    build-and-deploy:
        name: Build and deploy Gatsby site
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install Project Dependencies
              run: npm ci

            - name: Install Gatsby CLI
              run: npm install -g gatsby-cli@5.15.0

            # Cache Gatsby build files
            - uses: actions/cache@v4
              with:
                  path: |
                      .cache
                      public
                  key: ${{ runner.os }}-gatsby-build-${{ hashFiles('gatsby-config.ts', 'gatsby-node.ts', 'package-lock.json') }}
                  restore-keys: ${{ runner.os }}-gatsby-build-

            # Cache WordPress source data and media files
            - uses: actions/cache@v4
              with:
                  path: |
                      .cache/caches/gatsby-source-wordpress
                      .cache/data
                      .wordpress-cache
                  key: ${{ runner.os }}-wordpress-data-${{ hashFiles('gatsby-config.ts') }}
                  restore-keys: ${{ runner.os }}-wordpress-data-

            - name: 🔨 Build project
              run: npm run build

            - name: ✅ Verify build
              run: ls -la public

            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USER }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  local-dir: ./public/
                  server-dir: ${{ secrets.FTP_SERVERDIR }}
